services:
  db:
    image: postgres:16-alpine
    container_name: frethan_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frethan_db
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d frethan_db"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - frethan_pgdata:/var/lib/postgresql/data

volumes:
  frethan_pgdata:
